### ISSUE TITLE
Usage section contains wrong code

### ISSUE THREAD

**Issue by arnaud-cortisse** [yjb94/react-store-badges#2]
Hello,

Thanks for the package!

I noticed a typo in the 'Usage' section; 

`<ReactStoreBadges
          platfrom={'ios'}
          url={'YOUR_APP_STORE_URL'}
          locale={'en-us'}
 />`

it should be '**platform**' instead of 'platfrom'.

**Comment by yjb94** [comment]
thanks for your notice! fixed it right away
