### ISSUE TITLE
Url on new window

### ISSUE THREAD

**Issue by CMonjo** [yjb94/react-store-badges#4]
Hey ! :)

First : very cool package, thank's ! 

It would be interesting to add this feature : 

- props for open in a new window 
For something like this : 

`<ReactStoreBadges platform={'ios'} url={'YOUR_APP_STORE_URL'} locale={'en-us'} newWindow={true} />`

**Comment by yjb94** [comment]
@CMonjo thx for your idea.

added this feature in this [commit](https://github.com/yjb94/react-store-badges/commit/307b78297d5a6f114517158265a291baf6dac395), v1.5.0
